import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Download, FileJson, File } from 'lucide-react';
import jsPDF from 'jspdf';

export default function StrategyExporter({ strategy, responses, suggestedSolutions }) {
  const [exporting, setExporting] = useState(false);

  const generatePDF = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      let yPosition = 20;
      const lineHeight = 8;
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;

      const addText = (text, fontSize, isBold = false) => {
        doc.setFontSize(fontSize);
        doc.setFont(undefined, isBold ? 'bold' : 'normal');
        const lines = doc.splitTextToSize(text, maxWidth);
        doc.text(lines, margin, yPosition);
        yPosition += lines.length * lineHeight;
        return yPosition;
      };

      // Title
      doc.setFont(undefined, 'bold');
      doc.setFontSize(20);
      doc.text('AI Implementation Strategy Brief', margin, yPosition);
      yPosition += 15;

      // Input Summary
      addText('CLIENT CONTEXT', 12, true);
      yPosition += 2;
      addText(`Challenge: ${responses.business_challenge}`, 10);
      addText(`Current Stage: ${responses.current_state}`, 10);
      addText(`Timeline: ${responses.timeline}`, 10);
      addText(`Success Metric: ${responses.success_metric}`, 10);
      addText(`Budget: ${responses.budget}`, 10);
      yPosition += 3;

      // Executive Summary
      addText('EXECUTIVE SUMMARY', 12, true);
      yPosition += 2;
      addText(`Recommended Solution: ${strategy.recommendedSolution}`, 10);
      yPosition += 3;

      // Business Impact
      addText('EXPECTED BUSINESS IMPACT', 12, true);
      yPosition += 2;
      strategy.businessImpact.forEach(impact => {
        addText(`• ${impact}`, 10);
        yPosition += 2;
      });
      yPosition += 3;

      // Implementation Roadmap
      if (yPosition > pageHeight - 80) {
        doc.addPage();
        yPosition = 20;
      }
      addText('IMPLEMENTATION ROADMAP', 12, true);
      yPosition += 2;
      strategy.implementationRoadmap.forEach((phase, idx) => {
        addText(`Phase ${idx + 1}: ${phase.phase} (${phase.duration})`, 10, true);
        yPosition += 2;
        phase.deliverables.forEach(d => {
          addText(`  • ${d}`, 9);
          yPosition += 1.5;
        });
        yPosition += 2;
      });

      // Investment
      if (yPosition > pageHeight - 60) {
        doc.addPage();
        yPosition = 20;
      }
      addText('INVESTMENT & RESOURCES', 12, true);
      yPosition += 2;
      addText(`Estimated Investment: ${strategy.estimatedInvestment}`, 10);
      yPosition += 5;

      addText('REQUIRED CAPABILITIES', 12, true);
      yPosition += 2;
      strategy.requiredCapabilities.forEach(cap => {
        addText(`• ${cap}`, 10);
        yPosition += 2;
      });

      // Success & Risks
      if (yPosition > pageHeight - 60) {
        doc.addPage();
        yPosition = 20;
      }
      yPosition += 3;
      addText('SUCCESS FACTORS', 12, true);
      yPosition += 2;
      strategy.successFactors.forEach(factor => {
        addText(`• ${factor}`, 10);
        yPosition += 2;
      });

      yPosition += 3;
      addText('RISK FACTORS & MITIGATION', 12, true);
      yPosition += 2;
      strategy.riskFactors.forEach(risk => {
        addText(`• ${risk}`, 10);
        yPosition += 2;
      });

      // Next Steps
      if (yPosition > pageHeight - 50) {
        doc.addPage();
        yPosition = 20;
      }
      yPosition += 3;
      addText('IMMEDIATE NEXT STEPS', 12, true);
      yPosition += 2;
      strategy.nextSteps.forEach((s, idx) => {
        addText(`${idx + 1}. ${s}`, 10);
        yPosition += 3;
      });

      // Solutions
      if (suggestedSolutions) {
        if (yPosition > pageHeight - 40) {
          doc.addPage();
          yPosition = 20;
        }
        yPosition += 3;
        addText('RECOMMENDED INTINC SOLUTIONS', 12, true);
        yPosition += 2;
        addText(suggestedSolutions.matchRationale, 10);
        yPosition += 3;
        suggestedSolutions.matchedSolutions.forEach((sol, i) => {
          addText(`${i + 1}. ${sol}`, 10);
          yPosition += 2;
        });
      }

      // Footer
      doc.setFont(undefined, 'normal');
      doc.setFontSize(8);
      doc.text(
        `Generated by INTinc.com AI Strategy Wizard - ${new Date().toLocaleDateString()}`,
        margin,
        pageHeight - 10
      );

      doc.save('AI_Strategy_Brief.pdf');
      base44.analytics.track({ eventName: 'strategy_pdf_exported' });
    } catch (error) {
      console.error('PDF export failed:', error);
    } finally {
      setExporting(false);
    }
  };

  const generateJSON = () => {
    try {
      const exportData = {
        generatedAt: new Date().toISOString(),
        clientContext: responses,
        strategy,
        suggestedSolutions,
        version: '1.0'
      };

      const dataStr = JSON.stringify(exportData, null, 2);
      const dataBlob = new Blob([dataStr], { type: 'application/json' });
      const url = URL.createObjectURL(dataBlob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'AI_Strategy_Export.json';
      link.click();

      base44.analytics.track({ eventName: 'strategy_json_exported' });
    } catch (error) {
      console.error('JSON export failed:', error);
    }
  };

  const generateMarkdown = () => {
    try {
      const md = `# AI Implementation Strategy Brief

Generated: ${new Date().toLocaleDateString()}

## Client Context

- **Challenge:** ${responses.business_challenge}
- **Current Stage:** ${responses.current_state}
- **Desired Timeline:** ${responses.timeline}
- **Success Metric:** ${responses.success_metric}
- **Budget:** ${responses.budget}
- **Team Readiness:** ${responses.team_readiness}

## Executive Summary

**Recommended Solution:** ${strategy.recommendedSolution}

## Expected Business Impact

${strategy.businessImpact.map(impact => `- ${impact}`).join('\n')}

## Implementation Roadmap

${strategy.implementationRoadmap
  .map(
    (phase, i) => `
### Phase ${i + 1}: ${phase.phase}
**Duration:** ${phase.duration}

Deliverables:
${phase.deliverables.map(d => `- ${d}`).join('\n')}
`
  )
  .join('\n')}

## Investment & Resources

**Estimated Investment:** ${strategy.estimatedInvestment}

### Required Capabilities

${strategy.requiredCapabilities.map(cap => `- ${cap}`).join('\n')}

## Success & Risk Management

### Success Factors

${strategy.successFactors.map(factor => `- ${factor}`).join('\n')}

### Risk Factors

${strategy.riskFactors.map(risk => `- ${risk}`).join('\n')}

## Immediate Next Steps

${strategy.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

${
  suggestedSolutions
    ? `
## Recommended INTinc Solutions

${suggestedSolutions.matchRationale}

${suggestedSolutions.matchedSolutions.map((sol, i) => `- ${sol}`).join('\n')}
`
    : ''
}

---
*This strategy was generated by INTinc.com AI Strategy Wizard*`;

      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'AI_Strategy.md';
      link.click();

      base44.analytics.track({ eventName: 'strategy_markdown_exported' });
    } catch (error) {
      console.error('Markdown export failed:', error);
    }
  };

  return (
    <div className="grid md:grid-cols-3 gap-3">
      <button
        onClick={generatePDF}
        disabled={exporting}
        className="flex items-center justify-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed text-white"
      >
        <Download className="w-4 h-4" />
        PDF Report
      </button>
      <button
        onClick={generateMarkdown}
        disabled={exporting}
        className="flex items-center justify-center gap-2 px-6 py-3 bg-green-600 hover:bg-green-700 rounded-lg font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed text-white"
      >
        <File className="w-4 h-4" />
        Markdown
      </button>
      <button
        onClick={generateJSON}
        disabled={exporting}
        className="flex items-center justify-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 rounded-lg font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed text-white"
      >
        <FileJson className="w-4 h-4" />
        JSON Export
      </button>
    </div>
  );
}